### ISSUE TITLE
Currently failing on ChocolateyInstall step

### ISSUE THREAD

**Issue by iamforgettable** [rolando-anton/packer-disposable-windows#1]
Here are the details:

`packer build -only=qemu -var-file=windows-10-1903-iso.json -var-file=windows-10-qemu-vars.json -var-file=packer-creds.json -var-file=kvm-vars.json -except=gcp -var tag=golden windows-base.json`

>     qemu: Failures
>     qemu:  - googlechrome (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.
>     qemu:  See log for details.
>     qemu:
>     qemu:
>     qemu:     Directory: C:\Windows\Setup
>     qemu:
>     qemu:
>     qemu: Mode                LastWriteTime         Length Name
>     qemu: ----                -------------         ------ ----
>     qemu: d-----         1/6/2021  11:57 PM                Scripts
>     qemu:
>     qemu:
>     qemu:     Directory: C:\Windows
>     qemu:
>     qemu:
>     qemu: Mode                LastWriteTime         Length Name
>     qemu: ----                -------------         ------ ----
>     qemu: d-----         1/6/2021  11:57 PM                packer
> ==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
> ==> qemu: Deleting output directory...
> Build 'qemu' errored after 16 minutes 53 seconds: Script exited with non-zero exit status: 4294967295.Allowed exit codes are: [0]
> 

Could you advise on how to get more debug info here (if needed)?

**Comment by rolando-anton** [comment]
Hello, you can try to add: PACKER_LOG=1, so the command would be:

PACKER_LOG=1 packer build -only=qemu -var-file=windows-10-1903-iso.json -var-file=windows-10-qemu-vars.json -var-file=packer-creds.json -var-file=kvm-vars.json -except=gcp -var tag=golden windows-base.json

I had an issue once and it was because of an internet issue.

**Comment by iamforgettable** [comment]
Still fails on rerun - but I think the extra debug info is helpful:

>     qemu: Progress: 100% - Completed download of C:\Users\labadmin\AppData\Local\Temp\chocolatey\GoogleChrome\87.0.4280.88\googlechromestandaloneenterprise64.msi (68.96 MB).
>     qemu: Download of googlechromestandaloneenterprise64.msi (68.96 MB) completed.
>     qemu: Error - hashes do not match. Actual value was '70B7F4105474E6814BC0CF10542F6EFBED446DE5390AF86A54E32D6EABB060D8'.
>     qemu: ERROR: Checksum for 'C:\Users\labadmin\AppData\Local\Temp\chocolatey\GoogleChrome\87.0.4280.88\googlechromestandaloneenterprise64.msi' did not meet '019b2bb4df42194a0be7feac3e4f54d8843a7022b0e549c520c74296543ba965' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
>     qemu:   googlechrome may be able to be automatically uninstalled.

I can confirm that the download at that URL is really 70B7F4105474E6814BC0CF10542F6EFBED446DE5390AF86A54E32D6EABB060D8

Looks like a normal issue with Chocolatey:
https://www.gep13.co.uk/blog/chocolatey-error-hashes-do-not-match

I'll wait a day and see what happens.

Thanks for your help. This looks like a great project.
